import {JSDOM} from 'jsdom';
import {readFileSync,readdirSync} from 'node:fs';
import assert from 'node:assert/strict';
const dom=new JSDOM('<!doctype html><html><body><div id="root"></div></body></html>',{url:'https://dream.example',runScripts:'outside-only',pretendToBeVisual:true});
const {window:w}=dom;w.HTMLElement.prototype.scrollIntoView=function(){};
const bundle=readdirSync('dist/assets').find(f=>f.endsWith('.js'));
w.eval(readFileSync(`dist/assets/${bundle}`,'utf8'));
const wait=()=>new Promise(r=>setTimeout(r,45));
const $=s=>w.document.querySelector(s);
const click=async s=>{assert.ok($(s),s);$(s).click();await wait()};
await wait();
assert.equal(w.document.querySelectorAll('.product-card').length,4);
await click('.filters button:nth-child(3)');
assert.equal(w.document.querySelectorAll('.product-card').length,1);
assert.match($('.product-title').textContent,/পাওয়ার টিলার/);
await click('.filters button:first-child');
await click('.product-bottom button');
assert.equal(JSON.parse(w.localStorage.getItem('dream-cart'))[0].qty,1);
await click('.bag');
assert.ok($('.cart-item'));
await click('.quantity button:last-child');
assert.equal(JSON.parse(w.localStorage.getItem('dream-cart'))[0].qty,2);
await click('.quantity button:first-child');
assert.equal(JSON.parse(w.localStorage.getItem('dream-cart'))[0].qty,1);
await click('.cart-modal .btn.full');
const form=$('form');
form.querySelector('[name="name"]').value='ডেমো কৃষক';
form.querySelector('[type="tel"]').value='01234567890';
form.querySelector('textarea').value='ঝিনাইদহ, বাংলাদেশ';
await click('form button[type="submit"]');
assert.ok($('.success'));
assert.deepEqual(JSON.parse(w.localStorage.getItem('dream-cart')),[]);
await click('.close');
await click('.header-actions button:nth-child(2)');
$('form [name="name"]').value='ডেমো কৃষক';
$('form [name="phone"]').value='01234567890';
await click('form button[type="submit"]');
assert.equal(JSON.parse(w.localStorage.getItem('dream-account')).name,'ডেমো কৃষক');
await click('.modal .btn.full');
assert.equal(w.localStorage.getItem('dream-account'),null);
await click('.close');
await click('.product-photo');
assert.ok($('.detail-image'));
w.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape'}));await wait();
assert.equal($('.overlay'),null);
await click('.video-btn');
assert.match($('iframe').src,/JrYg28qdqZA/);
await click('.close');
await click('.floating-wa');
assert.match($('.toast').textContent,/ডেমো WhatsApp/);
console.log('PASS: catalogue, filters, cart add/quantity, checkout, local profile creation/deletion, product detail, Escape, YouTube and dummy WhatsApp.');
w.close();
