import React, {useState, useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight, ArrowRight, ShoppingBag, Search, UserRound, Phone, MapPin, ChevronDown, Menu, X, Truck, ShieldCheck, Headphones, Leaf, Play, Plus, Minus, Trash2, Check, MessageCircle, Sprout, Tractor, Wheat, Cog, CheckCircle2} from 'lucide-react';
import './style.css';
const bn=n=>n.toLocaleString('bn-BD');
const products=[
{id:0,name:'পেট্রোল গ্রাস কাটার',sub:'হালকা যন্ত্রে, ঘাস কাটুন অনায়াসে',category:'ঘাস কাটার মেশিন',price:32500,tag:'জনপ্রিয়',desc:'বাগান, জমির আইল ও বাড়ির আশপাশের ঘাস পরিষ্কারের জন্য বহনযোগ্য ব্রাশ কাটার। লম্বা শ্যাফট ও দুই হাতের হ্যান্ডেল দিয়ে সুবিধামতো নিয়ন্ত্রণ করা যায়।',features:['বহনযোগ্য ডিজাইন','পেট্রোলচালিত মেশিন','বাগান ও জমির আইলের জন্য']},
{id:1,name:'মিনি পাওয়ার টিলার',sub:'ছোট জমিতে, বড় কাজের সঙ্গী',category:'পাওয়ার টিলার',price:48500,tag:'সেরা পছন্দ',desc:'ছোট জমি ও সবজির বাগানের মাটি আলগা করা এবং চাষের প্রস্তুতিতে ব্যবহারযোগ্য কমপ্যাক্ট পাওয়ার টিলার। সহজে পরিচালনাযোগ্য গঠন ছোট পরিসরের কৃষিকাজে সহায়ক।',features:['কমপ্যাক্ট গঠন','মাটি প্রস্তুতির উপযোগী','সবজি বাগানে ব্যবহারযোগ্য']},
{id:2,name:'মিনি চাফ কাটার',sub:'খামারের খাবার তৈরি হবে সহজে',category:'ফিড প্রসেসিং',price:38000,tag:'খামারের সঙ্গী',desc:'গবাদিপশুর খাবারের জন্য ঘাস ও খড় ছোট টুকরায় কাটতে ব্যবহৃত চাফ কাটার। ছোট খামারের দৈনন্দিন খাদ্য প্রস্তুতির কাজ সহজ করতে উপযোগী।',features:['ঘাস ও খড় কাটার জন্য','স্ট্যান্ডসহ গঠন','ছোট খামারের উপযোগী']},
{id:3,name:'মিনি ফিড গ্রাইন্ডার',sub:'নিজের খামারের ফিড, নিজেই তৈরি করুন',category:'ফিড প্রসেসিং',price:42500,tag:'নতুন সংযোজন',desc:'খামারের খাদ্য উপকরণ হিসেবে শস্য গুঁড়া করার জন্য ছোট আকারের ফিড গ্রাইন্ডার। হপার দিয়ে উপকরণ দেওয়া যায় এবং স্ট্যান্ডের ওপর রেখে ব্যবহার করা যায়।',features:['শস্য গুঁড়া করার যন্ত্র','হপারসহ ডিজাইন','কম জায়গায় ব্যবহারযোগ্য']}
];
const categories=[['সব মেশিন',Sprout],['ঘাস কাটার মেশিন',Leaf],['পাওয়ার টিলার',Tractor],['ফিড প্রসেসিং',Wheat]];
function stored(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function App(){
 const [cart,setCart]=useState(()=>stored('dream-cart',[]));const [account,setAccount]=useState(()=>stored('dream-account',null));
 const [modal,setModal]=useState(null),[detail,setDetail]=useState(null),[category,setCategory]=useState('সব মেশিন'),[search,setSearch]=useState(''),[searchOpen,setSearchOpen]=useState(false),[menu,setMenu]=useState(false),[toast,setToast]=useState(''),[sort,setSort]=useState('default');
 const count=cart.reduce((a,c)=>a+c.qty,0),total=cart.reduce((a,c)=>a+products[c.id].price*c.qty,0);
 useEffect(()=>{localStorage.setItem('dream-cart',JSON.stringify(cart))},[cart]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(t)},[toast]);
 useEffect(()=>{const previous=document.activeElement;document.body.style.overflow=modal?'hidden':'';const close=e=>{if(e.key==='Escape')setModal(null);if(e.key==='Tab'&&modal){const items=[...document.querySelectorAll('[role="dialog"] button,[role="dialog"] a,[role="dialog"] input,[role="dialog"] textarea,[role="dialog"] iframe')].filter(el=>!el.disabled);const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};window.addEventListener('keydown',close);return()=>{document.body.style.overflow='';window.removeEventListener('keydown',close);previous?.focus()}},[modal]);
 function add(id){setCart(c=>c.some(x=>x.id===id)?c.map(x=>x.id===id?{...x,qty:x.qty+1}:x):[...c,{id,qty:1}]);setToast('মেশিনটি আপনার ব্যাগে যোগ হয়েছে')}
 function qty(id,n){setCart(c=>c.map(x=>x.id===id?{...x,qty:x.qty+n}:x).filter(x=>x.qty>0))}
 function wa(){setToast('এটি ডেমো WhatsApp বাটন। কোনো মেসেজ পাঠানো হয়নি।')}
 function go(cat='সব মেশিন'){setCategory(cat);setMenu(false);document.getElementById('products').scrollIntoView({behavior:'smooth'})}
 let visible=products.filter(p=>(category==='সব মেশিন'||p.category===category)&&(p.name+p.category+p.desc).includes(search));if(sort!=='default')visible.sort((a,b)=>sort==='low'?a.price-b.price:b.price-a.price);
 return <>
 <div className="announcement"><span><Sprout size={15}/> আধুনিক যন্ত্রে সমৃদ্ধ কৃষি, পাশে ড্রিম মেশিনারি</span><span><MapPin size={14}/> ঝিনাইদহ, বাংলাদেশ <i/> <Phone size={14}/> 01234567890</span></div>
 <header><a href="#" className="brand"><img src="/logo.svg" alt="ড্রিম মেশিনারি লোগো"/><div>ড্রিম মেশিনারি<small>DREAM MACHINERY</small></div></a><nav className={menu?'open':''}><a className="active" href="#" onClick={()=>setMenu(false)}>হোম</a><button onClick={()=>go()}>সকল মেশিন <ChevronDown size={14}/></button><a href="#story" onClick={()=>setMenu(false)}>আমাদের গল্প</a><a href="#why" onClick={()=>setMenu(false)}>কেন আমরা</a><a href="#contact" onClick={()=>setMenu(false)}>যোগাযোগ</a></nav><div className="header-actions"><button aria-label="পণ্য খুঁজুন" onClick={()=>setSearchOpen(!searchOpen)}><Search/></button><button aria-label="আপনার অ্যাকাউন্ট" onClick={()=>setModal('account')}><UserRound/></button><button className="bag" aria-label="শপিং ব্যাগ" onClick={()=>setModal('cart')}><ShoppingBag/><span>{bn(count)}</span></button><button className="menu-toggle" aria-label="মেনু" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
 {searchOpen&&<div className="search-bar"><Search size={20}/><input autoFocus placeholder="আপনার প্রয়োজনের মেশিন খুঁজুন…" value={search} onChange={e=>{setSearch(e.target.value);document.getElementById('products').scrollIntoView({behavior:'smooth'})}}/><button onClick={()=>{setSearch('');setSearchOpen(false)}} aria-label="সার্চ বন্ধ করুন"><X/></button></div>}
 <main>
 <section className="hero"><div className="hero-shade"/><div className="hero-content"><div className="eyebrow"><span/> কৃষির নতুন সম্ভাবনা</div><h1>পরিশ্রম হোক কম,<br/>ফসল হোক <em>বেশি।</em></h1><p>আপনার জমি ও খামারের জন্য আধুনিক মিনি মেশিন।<br/>সঠিক যন্ত্রে সহজ হোক কৃষি, এগিয়ে যাক আপনার স্বপ্ন।</p><div className="hero-buttons"><button className="btn gold" onClick={()=>go()}>আপনার মেশিন খুঁজুন <ArrowUpRight size={20}/></button><button className="video-btn" onClick={()=>setModal('video')}><span><Play size={15} fill="currentColor"/></span> আমাদের ভিডিও দেখুন</button></div><div className="hero-note"><ShieldCheck size={18}/> আপনার কৃষিকাজের বিশ্বস্ত সঙ্গী <span>•</span> ঝিনাইদহ থেকে সারা দেশে</div></div><div className="hero-card"><div className="hero-card-icon"><Leaf size={23}/></div><div>ছোট মেশিন, বড় সম্ভাবনা<small>আধুনিক কৃষির পথে একসাথে</small></div><ArrowUpRight size={22}/></div><div className="hero-caption">কৃষি বদলালে, বদলাবে আগামী। <span>ঝিনাইদহ • বাংলাদেশ</span></div></section>
 <section className="benefits"><div><Truck/><span>দেশজুড়ে ডেলিভারি<small>আপনার দোরগোড়ায় মেশিন</small></span></div><div><ShoppingBag/><span>ক্যাশ অন ডেলিভারি<small>পণ্য হাতে পেয়ে মূল্য পরিশোধ</small></span></div><div><ShieldCheck/><span>বেছে নেওয়া মেশিন<small>আপনার কাজের প্রয়োজন অনুযায়ী</small></span></div><div><Headphones/><span>সহজে পরামর্শ নিন<small>সঠিক মেশিন বাছাইয়ে সহায়তা</small></span></div></section>
 <section id="products" className="products section"><div className="section-top"><div><div className="overline"><span/> আপনার কাজের সঠিক সঙ্গী</div><h2>কৃষি হবে আরও সহজ</h2><p>জমি থেকে খামার—প্রতিটি কাজের জন্য প্রয়োজনীয় মেশিন।</p></div><button className="text-link" onClick={()=>{setSearch('');setSort('default');go()}}>সব মেশিন দেখুন <ArrowUpRight size={18}/></button></div><div className="product-toolbar"><div className="filters">{categories.map(([label,Icon])=><button key={label} className={category===label?'selected':''} onClick={()=>setCategory(label)}><Icon size={17}/>{label}</button>)}</div><label className="sort"><span>সাজান:</span><select aria-label="মূল্য অনুযায়ী সাজান" value={sort} onChange={e=>setSort(e.target.value)}><option value="default">নির্বাচিত মেশিন</option><option value="low">দাম কম থেকে বেশি</option><option value="high">দাম বেশি থেকে কম</option></select></label></div><div className="product-grid">{visible.map(p=><article className="product-card" key={p.id}><button className="product-photo" onClick={()=>{setDetail(p);setModal('detail')}} aria-label={`${p.name} বিস্তারিত`}><span className={'product-tag tag-'+p.id}>{p.tag}</span><img src={`/images/machine-${p.id}.webp`} alt={p.name}/><span className="photo-view">বিস্তারিত দেখুন <ArrowUpRight size={15}/></span></button><div className="product-info"><div className="product-category">{p.category} <span><span/> প্রদর্শনী পণ্য</span></div><button className="product-title" onClick={()=>{setDetail(p);setModal('detail')}}>{p.name}</button><p>{p.sub}</p><div className="product-bottom"><div><strong>৳ {bn(p.price)}</strong><small>নমুনা মূল্য</small></div><button aria-label={`${p.name} ব্যাগে যোগ করুন`} onClick={()=>add(p.id)}><Plus size={19}/><ShoppingBag size={18}/></button></div></div></article>)}</div>{visible.length===0&&<div className="empty">কোনো মেশিন পাওয়া যায়নি। <button onClick={()=>{setSearch('');setCategory('সব মেশিন')}}>সব মেশিন দেখুন</button></div>}<div className="catalog-note"><Leaf size={15}/> আপনার কাজ বুঝে, সঠিক মেশিন বেছে নিন। <button onClick={wa}>পরামর্শ নিতে কথা বলুন <ArrowRight size={15}/></button></div></section>
 <section className="story section" id="story"><div className="story-media"><img src="/images/hero.webp" alt="সবুজ জমিতে মিনি পাওয়ার টিলার" loading="lazy"/><div className="video-label"><span/> ড্রিম মেশিনারির গল্প</div><button className="play-large" aria-label="মালিকের ভিডিও দেখুন" onClick={()=>setModal('video')}><Play fill="currentColor"/></button><div className="media-caption">আমাদের কথা, আমাদের স্বপ্ন।<small>সরাসরি শুনুন আমাদের কাছ থেকে</small></div></div><div className="story-copy"><div className="overline"><span/> মাটির সাথে, মানুষের পাশে</div><h2>আপনার স্বপ্নের চাষে,<br/>আমরাও আছি পাশে।</h2><p>কৃষি শুধু কাজ নয়, আমাদের জীবনের গল্প। সেই গল্পে পরিশ্রম একটু কমিয়ে, সম্ভাবনা আরও বাড়াতে ড্রিম মেশিনারির পথচলা।</p><p>ঝিনাইদহ থেকে আমরা পরিচয় করিয়ে দিচ্ছি ছোট জমি ও খামারের উপযোগী কৃষিযন্ত্রের সঙ্গে। আপনার প্রয়োজন বুঝে সঠিক মেশিন বেছে নেওয়াই আমাদের লক্ষ্য।</p><div className="story-sign"><img src="/logo.svg" alt=""/><div>ড্রিম মেশিনারি পরিবার<small>ঝিনাইদহ, বাংলাদেশ</small></div></div><button className="text-link" onClick={()=>setModal('video')}>আমাদের গল্প দেখুন <ArrowUpRight size={18}/></button></div></section>
 <section className="why section" id="why"><div className="overline"><span/> সহজ কেনাকাটা, নিশ্চিন্ত পথচলা</div><h2>আপনার প্রয়োজন, আমাদের অগ্রাধিকার</h2><div className="why-grid"><div><span>০১</span><Tractor/><h3>কাজ বুঝে মেশিন</h3><p>ছোট জমি, বাগান কিংবা খামার—আপনার কাজের সঙ্গে মানানসই যন্ত্র খুঁজুন।</p></div><div><span>০২</span><MessageCircle/><h3>সরাসরি কথা বলুন</h3><p>কেনার আগে মেশিন সম্পর্কে জানুন, আপনার প্রশ্নের উত্তর খুঁজে নিন।</p></div><div><span>০৩</span><Truck/><h3>সহজ অর্ডার প্রক্রিয়া</h3><p>পছন্দের মেশিন ব্যাগে রাখুন এবং ক্যাশ অন ডেলিভারির ডেমো দেখুন।</p></div></div></section>
 <section className="contact-banner section" id="contact"><div className="contact-icon"><Headphones size={43}/></div><div><h2>কোন মেশিনটি আপনার জন্য সঠিক?</h2><p>আপনার প্রয়োজন জানান। আসুন, একসাথে সঠিক মেশিনটি বেছে নিই।</p></div><button className="btn gold" onClick={wa}><MessageCircle size={20}/> WhatsApp-এ কথা বলুন <ArrowUpRight size={18}/></button></section>
 </main><footer><div className="footer-main"><div className="footer-brand"><a href="#" className="brand"><img src="/logo.svg" alt=""/><div>ড্রিম মেশিনারি<small>DREAM MACHINERY</small></div></a><p>আধুনিক যন্ত্রে সহজ কৃষি।<br/>আপনার পরিশ্রমের পাশে, স্বপ্নের সাথে।</p><span className="footer-location"><MapPin size={16}/> ঝিনাইদহ, বাংলাদেশ</span></div><div><h4>আমাদের মেশিন</h4>{categories.slice(1).map(([c])=><button key={c} onClick={()=>go(c)}>{c}</button>)}</div><div><h4>প্রয়োজনীয় লিংক</h4><a href="#story">আমাদের গল্প</a><button onClick={()=>setModal('delivery')}>ডেলিভারি ও পেমেন্ট</button><button onClick={()=>setModal('account')}>আমার অ্যাকাউন্ট</button></div><div><h4>যোগাযোগ করুন</h4><span><Phone size={16}/> 01234567890</span><span><MapPin size={16}/> ঝিনাইদহ, বাংলাদেশ</span><button className="footer-wa" onClick={wa}><MessageCircle size={16}/> WhatsApp মেসেজ <ArrowUpRight size={15}/></button></div></div><div className="footer-bottom"><span>© {bn(new Date().getFullYear())} ড্রিম মেশিনারি। সর্বস্বত্ব সংরক্ষিত।</span><span>ফ্রন্টএন্ড ডেমো • ছবি AI-নির্মিত • মূল্য নমুনা</span><span>মাটি ও মানুষের জন্য <Leaf size={13}/></span></div></footer>
 <button className="floating-wa" aria-label="ডেমো WhatsApp" onClick={wa}><MessageCircle size={25}/></button>
 {toast&&<div className="toast" role="status"><CheckCircle2 size={20}/>{toast}</div>}
 {modal&&<div className="overlay" onClick={()=>setModal(null)}><section role="dialog" aria-modal="true" aria-label="ড্রিম মেশিনারি" className={`modal ${modal==='cart'?'cart-modal':''} ${modal==='video'?'video-modal':''}`} onClick={e=>e.stopPropagation()}><button autoFocus className="close" aria-label="বন্ধ করুন" onClick={()=>setModal(null)}><X/></button>
 {modal==='video'&&<><h2>ড্রিম মেশিনারির গল্প</h2><iframe src="https://www.youtube.com/embed/JrYg28qdqZA?autoplay=1" title="ড্রিম মেশিনারির ভিডিও" allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen/><p>ভিডিও না চললে <a href="https://youtu.be/JrYg28qdqZA" target="_blank" rel="noreferrer">YouTube-এ দেখুন ↗</a></p></>}
 {modal==='detail'&&detail&&<><img className="detail-image" src={`/images/machine-${detail.id}.webp`} alt={detail.name}/><div className="overline">{detail.category}</div><h2>{detail.name}</h2><p>{detail.desc}</p><ul className="feature-list">{detail.features.map(f=><li key={f}><Check size={17}/>{f}</li>)}</ul><p className="demo-note">ছবি AI-নির্মিত ও মূল্য নমুনা। প্রকৃত মডেল, ক্ষমতা, যন্ত্রাংশ ও ওয়ারেন্টি কেনার আগে নিশ্চিত করুন।</p><div className="detail-bottom"><strong>৳ {bn(detail.price)}</strong><button className="btn green" onClick={()=>add(detail.id)}><ShoppingBag size={18}/> ব্যাগে যোগ করুন</button></div></>}
 {modal==='cart'&&<><h2>আপনার শপিং ব্যাগ <small>({bn(count)})</small></h2>{cart.length?<><div className="cart-items">{cart.map(c=>{const p=products[c.id];return <div className="cart-item" key={c.id}><img src={`/images/machine-${p.id}.webp`} alt={p.name}/><div><h3>{p.name}</h3><strong>৳ {bn(p.price)}</strong><div className="quantity"><button aria-label="পরিমাণ কমান" onClick={()=>qty(c.id,-1)}><Minus size={15}/></button><span>{bn(c.qty)}</span><button aria-label="পরিমাণ বাড়ান" onClick={()=>qty(c.id,1)}><Plus size={15}/></button></div></div><button aria-label="পণ্য সরান" onClick={()=>setCart(cart.filter(x=>x.id!==c.id))}><Trash2 size={18}/></button></div>})}</div><div className="total"><span>সর্বমোট</span><strong>৳ {bn(total)}</strong></div><p className="demo-note">ডেমো অর্ডার — কোনো প্রকৃত পেমেন্ট বা ডেলিভারি হবে না।</p><button className="btn green full" onClick={()=>setModal('checkout')}>অর্ডার করতে এগিয়ে যান <ArrowRight size={18}/></button></>:<div className="empty"><ShoppingBag size={45}/><h3>আপনার ব্যাগ এখনো খালি</h3><p>পছন্দের মেশিনটি ব্যাগে যোগ করুন।</p><button className="btn green" onClick={()=>{setModal(null);go()}}>মেশিন দেখুন</button></div>}</>}
 {modal==='account'&&<><div className="modal-icon"><UserRound/></div><h2>{account?`স্বাগতম, ${account.name}`:'আপনার অ্যাকাউন্ট তৈরি করুন'}</h2>{account?<><p>আপনার ডেমো প্রোফাইল শুধু এই ব্রাউজারে সংরক্ষিত আছে।</p><p><b>ফোন:</b> {account.phone}</p><button className="btn green full" onClick={()=>{setAccount(null);localStorage.removeItem('dream-account');setToast('স্থানীয় প্রোফাইল মুছে দেওয়া হয়েছে')}}>প্রোফাইল মুছুন</button></>:<><p>সহজ কেনাকাটার জন্য আপনার পরিচিতি রাখুন।</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.target);const a={name:f.get('name'),phone:f.get('phone')};setAccount(a);localStorage.setItem('dream-account',JSON.stringify(a));setToast('ডেমো অ্যাকাউন্ট তৈরি হয়েছে')}}><label>আপনার নাম<input required name="name" autoComplete="name" placeholder="সম্পূর্ণ নাম" maxLength={60}/></label><label>মোবাইল নম্বর<input required name="phone" type="tel" pattern="01[0-9]{9}" placeholder="01XXXXXXXXX" title="ইংরেজি অঙ্কে ১১ সংখ্যার বাংলাদেশি নম্বর" autoComplete="tel"/></label><p className="demo-note">এটি লগইন বা নিরাপদ অ্যাকাউন্ট নয়। কোনো পাসওয়ার্ড প্রয়োজন নেই; তথ্য শুধু আপনার ব্রাউজারে থাকবে।</p><button className="btn green full" type="submit">ডেমো অ্যাকাউন্ট তৈরি করুন <ArrowRight size={18}/></button></form></>}</>}
 {modal==='checkout'&&<><h2>অর্ডারের তথ্য</h2><p className="demo-note">এটি শুধুই ডেমো। আপনার তথ্য কোথাও পাঠানো হবে না।</p><form onSubmit={e=>{e.preventDefault();setCart([]);setModal('success')}}><label>আপনার নাম<input required name="name" defaultValue={account?.name} autoComplete="name" placeholder="সম্পূর্ণ নাম"/></label><label>মোবাইল নম্বর<input required type="tel" defaultValue={account?.phone} pattern="01[0-9]{9}" title="ইংরেজি অঙ্কে ১১ সংখ্যার বাংলাদেশি নম্বর" placeholder="01XXXXXXXXX"/></label><label>সম্পূর্ণ ঠিকানা<textarea required placeholder="গ্রাম / সড়ক, উপজেলা, জেলা" minLength={8}/></label><div className="cod"><CheckCircle2 size={20}/><div>ক্যাশ অন ডেলিভারি<small>পণ্য হাতে পেয়ে মূল্য পরিশোধ (ডেমো)</small></div></div><div className="total"><span>পণ্যের মোট মূল্য</span><strong>৳ {bn(total)}</strong></div><small>ডেলিভারি চার্জ এই ডেমোতে প্রযোজ্য নয়।</small><button className="btn green full" type="submit">ডেমো অর্ডার নিশ্চিত করুন <Check size={18}/></button></form></>}
 {modal==='success'&&<div className="success"><CheckCircle2 size={60}/><h2>ডেমো অর্ডার সম্পন্ন!</h2><p>অর্ডার প্রক্রিয়াটি দেখে নেওয়ার জন্য ধন্যবাদ। কোনো প্রকৃত অর্ডার তৈরি হয়নি, অর্থ কাটা হয়নি বা তথ্য পাঠানো হয়নি।</p><button className="btn green" onClick={()=>setModal(null)}>কেনাকাটায় ফিরে যান</button></div>}
 {modal==='delivery'&&<><h2>ডেলিভারি ও পেমেন্ট</h2><p>এই ওয়েবসাইটটি একটি ফ্রন্টএন্ড প্রদর্শনী। ক্যাশ অন ডেলিভারি ও দেশজুড়ে ডেলিভারির তথ্য এখানে সম্ভাব্য সেবার উপস্থাপনা, নিশ্চিত সেবার প্রতিশ্রুতি নয়।</p><p>চেকআউট সম্পন্ন করলে কোনো বাস্তব অর্ডার, পেমেন্ট বা ডেলিভারি তৈরি হয় না। প্রকৃত ডেলিভারি চার্জ, সময়সীমা, রিটার্ন ও ওয়ারেন্টি নীতি এখনো নির্ধারিত হয়নি।</p></>}
 </section></div>}
 </>;
}
createRoot(document.getElementById('root')).render(<App/>);
